//! Helix dynamics — the locked beehive formulas, ported for rotating machines.
//!
//! Provenance: direct port of the audio project's foundation engine,
//! `beehive/encode.py` @ 2a9eda5 — `_curvature_torsion` (l.47-59, the
//! corrected closed forms with the `omega^4 r0^2` term under the root),
//! `_smooth` (l.62-66) and `derive_dynamics` (l.69-121). Nothing is imported
//! from the audio project; parity is enforced by `tests/parity.rs` against a
//! fixture generated by the Python source itself.
//!
//! Two deliberate deviations, both documented where they occur:
//!  * colour (chroma/hue/sat/val) is dropped — vibration has no chroma;
//!  * boxcar smoothing uses the mean over the *clipped* window at the array
//!    edges instead of numpy's `mode="same"` zero padding. See [`smooth`].

/// Mirror of `np.gradient(x)` (unit spacing): central differences in the
/// interior, one-sided at the two ends. `beehive/encode.py` l.95-96, 110-111.
pub fn gradient(x: &[f64]) -> Vec<f64> {
    let n = x.len();
    match n {
        0 => Vec::new(),
        1 => vec![0.0],
        _ => {
            let mut g = Vec::with_capacity(n);
            g.push(x[1] - x[0]);
            for i in 1..n - 1 {
                g.push((x[i + 1] - x[i - 1]) * 0.5);
            }
            g.push(x[n - 1] - x[n - 2]);
            g
        }
    }
}

/// Boxcar smoothing, `beehive/encode.py::_smooth` (l.62-66) — with one fixed
/// deviation. The source uses `np.convolve(x, ones(k)/k, mode="same")`, whose
/// implicit zero padding makes the output droop toward zero within k/2 of both
/// ends. In a streaming monitor the newest revolution is *always* at an edge,
/// so the droop is a moving artifact on exactly the sample you act on. Here
/// the edge mean is taken over the samples actually inside the window, so a
/// constant input stays constant everywhere. Interior samples are identical
/// to the source; `tests/parity.rs` checks both facts.
pub fn smooth(x: &[f64], k: usize) -> Vec<f64> {
    if k <= 1 || x.is_empty() {
        return x.to_vec();
    }
    let n = x.len();
    let half_lo = (k - 1) / 2; // np.convolve "same" window placement for even/odd k
    let half_hi = k / 2;
    let mut out = Vec::with_capacity(n);
    for i in 0..n {
        let lo = i.saturating_sub(half_lo);
        let hi = (i + half_hi + 1).min(n);
        let s: f64 = x[lo..hi].iter().sum();
        out.push(s / (hi - lo) as f64);
    }
    out
}

const EPS: f64 = 1e-10; // beehive/encode.py l.43

/// Corrected Frenet curvature/torsion closed forms for the helix
/// `R(n) = (r0 cos wn, r0 sin wn, h(n))`, parametrised by n.
/// Port of `beehive/encode.py::_curvature_torsion` (l.47-59); note the
/// `omega^4 r0^2` term under the root — the typo fixed in the audio project.
pub fn curvature_torsion(
    omega: f64,
    r0: f64,
    h1: &[f64],
    h2: &[f64],
    h3: &[f64],
) -> (Vec<f64>, Vec<f64>) {
    let n = h1.len();
    let mut kappa = Vec::with_capacity(n);
    let mut tau = Vec::with_capacity(n);
    for i in 0..n {
        let common = omega.powi(4) * r0 * r0 + omega * omega * h1[i] * h1[i] + h2[i] * h2[i];
        let cross_norm = r0 * omega * common.sqrt();
        let speed_sq = omega * omega * r0 * r0 + h1[i] * h1[i];
        kappa.push(cross_norm / speed_sq.powf(1.5));
        tau.push(omega * (omega * omega * h1[i] + h3[i]) / common.max(EPS));
    }
    (kappa, tau)
}

/// Population standard deviation (numpy default, ddof=0), with the source's
/// `dA.std() or 1.0` guard against a zero std (l.97-98).
fn std_or_one(x: &[f64]) -> f64 {
    if x.is_empty() {
        return 1.0;
    }
    let m = x.iter().sum::<f64>() / x.len() as f64;
    let v = x.iter().map(|v| (v - m) * (v - m)).sum::<f64>() / x.len() as f64;
    let s = v.sqrt();
    if s == 0.0 {
        1.0
    } else {
        s
    }
}

/// Scalar meta for the dynamics — the bearing analogue of the record meta
/// consumed by `derive_dynamics` (`beehive/encode.py` l.85-91).
#[derive(Clone, Copy, Debug)]
pub struct DynamicsMeta {
    /// rad per index step. In the audio engine n is the hop/frame index and a
    /// *bar* is one 2π turn. Here n is the revolution index and one turn is
    /// `TURN_REVS` revolutions — the concrete resolution of the framework's
    /// open "what n takes" question for machines (theory/00).
    pub omega_n: f64,
    pub r0: f64,
    pub smooth_frames: usize,
    pub w_amp: f64,
    pub w_int: f64,
}

/// One turn of the machine helix = this many shaft revolutions (theory/00).
pub const TURN_REVS: usize = 64;

impl Default for DynamicsMeta {
    fn default() -> Self {
        DynamicsMeta {
            omega_n: 2.0 * std::f64::consts::PI / TURN_REVS as f64,
            r0: 1.0,
            smooth_frames: 1,
            w_amp: 1.0,
            w_int: 1.0,
        }
    }
}

/// Everything geometric, derived from the independent state (A, I).
#[derive(Clone, Debug, Default)]
pub struct Dynamics {
    pub d_a: Vec<f64>,
    pub d_i: Vec<f64>,
    pub f_mag: Vec<f64>,
    pub h: Vec<f64>,
    pub alpha: Vec<f64>,
    pub x: Vec<f64>,
    pub y: Vec<f64>,
    pub z: Vec<f64>,
    pub kappa: Vec<f64>,
    pub tau: Vec<f64>,
}

/// Port of `beehive/encode.py::derive_dynamics` (l.69-121), minus colour.
///
/// State s(n) = (A, I) → force F = ds/dn (each component normalised by its own
/// population std so ||F|| is dimensionless — the source's resolution of the
/// open weighting thread) → climb h = Σ||F|| → angle α = ω·n → position
/// R(n) = (r0 cos α, r0 sin α, h) → corrected κ, τ.
pub fn derive_dynamics(a: &[f64], i: &[f64], meta: &DynamicsMeta) -> Dynamics {
    assert_eq!(a.len(), i.len(), "state components must be equal length");
    let n = a.len();
    if n == 0 {
        return Dynamics::default();
    }

    let d_a = gradient(&smooth(a, meta.smooth_frames));
    let d_i = gradient(&smooth(i, meta.smooth_frames));
    let s_a = std_or_one(&d_a);
    let s_i = std_or_one(&d_i);

    let f_mag: Vec<f64> = d_a
        .iter()
        .zip(&d_i)
        .map(|(da, di)| {
            let fa = meta.w_amp * da / s_a;
            let fi = meta.w_int * di / s_i;
            (fa * fa + fi * fi).sqrt()
        })
        .collect();

    // climb = integral ||F|| (running sum, l.101)
    let mut h = Vec::with_capacity(n);
    let mut acc = 0.0;
    for f in &f_mag {
        acc += f;
        h.push(acc);
    }

    let alpha: Vec<f64> = (0..n).map(|k| meta.omega_n * k as f64).collect();
    let x: Vec<f64> = alpha.iter().map(|a| meta.r0 * a.cos()).collect();
    let y: Vec<f64> = alpha.iter().map(|a| meta.r0 * a.sin()).collect();
    let z = h.clone();

    let h2 = gradient(&f_mag);
    let h3 = gradient(&h2);
    let (kappa, tau) = curvature_torsion(meta.omega_n, meta.r0, &f_mag, &h2, &h3);

    Dynamics { d_a, d_i, f_mag, h, alpha, x, y, z, kappa, tau }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gradient_matches_numpy_semantics() {
        // np.gradient([0, 1, 4, 9, 16]) == [1, 2, 4, 6, 7]
        let g = gradient(&[0.0, 1.0, 4.0, 9.0, 16.0]);
        assert_eq!(g, vec![1.0, 2.0, 4.0, 6.0, 7.0]);
    }

    #[test]
    fn smoothing_keeps_constants_constant_at_the_edges() {
        // The documented deviation: numpy's mode="same" would droop the first
        // and last samples of a constant array toward zero; ours must not.
        let x = vec![5.0; 32];
        for k in [2usize, 3, 5, 8] {
            let s = smooth(&x, k);
            for v in s {
                assert!((v - 5.0).abs() < 1e-12, "edge droop at k={k}");
            }
        }
    }

    #[test]
    fn constant_state_has_zero_torsion_and_circle_curvature() {
        // A static machine: state never moves => ||F||=0, no climb, tau=0,
        // kappa = 1/r0 (a circle). Mirrors the zinc repo's helix invariant.
        let a = vec![-30.0; 128];
        let i = vec![2.0; 128];
        let meta = DynamicsMeta::default();
        let d = derive_dynamics(&a, &i, &meta);
        assert!(d.h.iter().all(|&v| v == 0.0), "no climb on a static state");
        for (k, t) in d.kappa.iter().zip(&d.tau) {
            assert!((k - 1.0 / meta.r0).abs() < 1e-9);
            assert!(t.abs() < 1e-12);
        }
    }

    #[test]
    fn moving_state_climbs_monotonically() {
        let a: Vec<f64> = (0..256).map(|n| (n as f64 * 0.1).sin() * 6.0 - 30.0).collect();
        let i: Vec<f64> = (0..256).map(|n| (n as f64 * 0.07).cos() * 3.0).collect();
        let d = derive_dynamics(&a, &i, &DynamicsMeta::default());
        assert!(d.h.windows(2).all(|w| w[1] >= w[0]), "climb is nondecreasing");
        assert!(*d.h.last().unwrap() > 0.0);
    }
}
