/* C ABI smoke test: consume a .bee exactly the way a platform host
 * (Swift/Kotlin/C#) will — open, read meta, PCM and side-channel, round-trip
 * a rewrite through bee_write_file, reopen, compare PCM bytes.
 *
 * Usage: smoke <file.bee> <expected_sample_rate> <expected_channels>
 * Exit 0 = all checks pass.
 */

#include "../crates/bee-ffi/include/bee.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int failures = 0;
#define CHECK(cond, msg)                                                       \
  do {                                                                         \
    if (cond) {                                                                \
      printf("  PASS  %s\n", msg);                                             \
    } else {                                                                   \
      printf("  FAIL  %s (last error: %s)\n", msg, bee_last_error());          \
      failures++;                                                              \
    }                                                                          \
  } while (0)

int main(int argc, char **argv) {
  if (argc != 4) {
    fprintf(stderr, "usage: smoke <file.bee> <sample_rate> <channels>\n");
    return 2;
  }
  const char *path = argv[1];
  uint32_t want_sr = (uint32_t)atoi(argv[2]);
  uint32_t want_ch = (uint32_t)atoi(argv[3]);

  BeeHandle *h = bee_open(path);
  CHECK(h != NULL, "bee_open");
  if (!h)
    return 1;

  CHECK(bee_sample_rate(h) == want_sr, "sample rate matches");
  CHECK(bee_channels(h) == want_ch, "channel count matches");
  CHECK(bee_frames(h) > 0, "frames > 0");

  uint64_t pcm_len = 0;
  const uint8_t *pcm = bee_pcm_bytes(h, &pcm_len);
  CHECK(pcm != NULL && pcm_len > 0, "pcm buffer present");

  uint64_t n = 0;
  const float *a = bee_helix_field(h, "A", &n);
  CHECK(a != NULL && n == bee_helix_frames(h), "helix field A has n_frames");
  const float *chroma = bee_helix_field(h, "chroma", &n);
  CHECK(chroma != NULL && n == bee_helix_frames(h) * bee_helix_chroma_bins(h),
        "chroma is frames x bins");
  CHECK(bee_helix_field(h, "nope", &n) == NULL && n == 0,
        "unknown field rejected");

  const char *manifest = bee_manifest_json(h);
  CHECK(manifest && strstr(manifest, "\"bee_format_version\":0") != NULL,
        "manifest json present");

  /* Rewrite through the C API and confirm the decoded PCM is bit-identical. */
  const char *meta = bee_helix_meta_json(h);
  char audio_meta[512];
  const char *dtype_names[] = {"int16", "int32", "float32", "float64"};
  snprintf(audio_meta, sizeof audio_meta,
           "{\"sample_rate\":%u,\"channels\":%u,\"subtype\":\"FLOAT\","
           "\"frames\":%llu,\"dtype\":\"%s\"}",
           bee_sample_rate(h), bee_channels(h),
           (unsigned long long)bee_frames(h), dtype_names[bee_dtype(h)]);
  /* Re-extract the npz verbatim is not exposed; write with an empty-meta
   * side-channel is invalid v0 — so reuse the original file's Layer 2 by
   * writing PCM through a fresh temp .bee built from this handle's fields
   * is out of scope for the C surface. Instead: round-trip PCM only, using
   * a minimal side-channel npz generated by the test driver. */
  const char *npz_path = getenv("SMOKE_NPZ");
  int32_t wrote = -1;
  char tmp_path[1024];
  if (npz_path) {
    FILE *f = fopen(npz_path, "rb");
    if (f) {
      fseek(f, 0, SEEK_END);
      long npz_len = ftell(f);
      fseek(f, 0, SEEK_SET);
      uint8_t *npz = malloc((size_t)npz_len);
      fread(npz, 1, (size_t)npz_len, f);
      fclose(f);
      snprintf(tmp_path, sizeof tmp_path, "%s.smoke.bee", path);
      wrote = bee_write_file(tmp_path, pcm, pcm_len, audio_meta, npz,
                             (uint64_t)npz_len, meta);
      free(npz);
    }
    CHECK(wrote == 0, "bee_write_file");
    if (wrote == 0) {
      BeeHandle *h2 = bee_open(tmp_path);
      CHECK(h2 != NULL, "reopen rewritten .bee");
      if (h2) {
        uint64_t len2 = 0;
        const uint8_t *pcm2 = bee_pcm_bytes(h2, &len2);
        CHECK(len2 == pcm_len && memcmp(pcm, pcm2, (size_t)pcm_len) == 0,
              "rewritten PCM bit-identical");
        bee_close(h2);
      }
      remove(tmp_path);
    }
  }

  bee_close(h);
  printf("smoke: %s\n", failures ? "FAILED" : "all checks passed");
  return failures ? 1 : 0;
}
