//! Geometry parity against the audio project's Python source.
//!
//! Fixtures under tests/fixtures/ are generated by make_fixture.py, which runs
//! the REAL `beehive.encode.derive_dynamics` / `_smooth` — so this test pins
//! the Rust port to the source of truth, not to a transcription of it.

use bearing_helix_research::geometry::{derive_dynamics, smooth, DynamicsMeta};

fn load_tsv(name: &str) -> (Vec<String>, Vec<Vec<f64>>) {
    let path = format!("{}/tests/fixtures/{}", env!("CARGO_MANIFEST_DIR"), name);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("missing fixture {path}: {e} (run make_fixture.py)"));
    let mut lines = text.lines().filter(|l| !l.starts_with('#'));
    let header: Vec<String> = lines
        .next()
        .expect("fixture header")
        .split('\t')
        .map(str::to_string)
        .collect();
    let rows = lines
        .map(|l| l.split('\t').map(|v| v.parse::<f64>().expect("float")).collect())
        .collect();
    (header, rows)
}

fn col(header: &[String], rows: &[Vec<f64>], name: &str) -> Vec<f64> {
    let j = header.iter().position(|h| h == name).unwrap_or_else(|| panic!("col {name}"));
    rows.iter().map(|r| r[j]).collect()
}

fn assert_close(name: &str, got: &[f64], want: &[f64], tol: f64) {
    assert_eq!(got.len(), want.len(), "{name} length");
    for (i, (g, w)) in got.iter().zip(want).enumerate() {
        let scale = 1.0_f64.max(w.abs());
        assert!(
            (g - w).abs() <= tol * scale,
            "{name}[{i}]: got {g:.17}, python {w:.17}, |Δ|={:.3e}",
            (g - w).abs()
        );
    }
}

#[test]
fn dynamics_match_the_python_engine() {
    let (header, rows) = load_tsv("dynamics_parity.tsv");
    let a = col(&header, &rows, "A");
    let i = col(&header, &rows, "I");
    let meta = DynamicsMeta {
        omega_n: 2.0 * std::f64::consts::PI / 64.0,
        r0: 1.0,
        smooth_frames: 1,
        w_amp: 1.0,
        w_int: 1.3,
    };
    let d = derive_dynamics(&a, &i, &meta);
    assert_close("dA", &d.d_a, &col(&header, &rows, "dA"), 1e-9);
    assert_close("dI", &d.d_i, &col(&header, &rows, "dI"), 1e-9);
    assert_close("F_mag", &d.f_mag, &col(&header, &rows, "F_mag"), 1e-9);
    assert_close("h", &d.h, &col(&header, &rows, "h"), 1e-9);
    assert_close("kappa", &d.kappa, &col(&header, &rows, "kappa"), 1e-9);
    assert_close("tau", &d.tau, &col(&header, &rows, "tau"), 1e-9);
}

#[test]
fn smoothing_matches_python_interior_and_fixes_the_edges() {
    let (header, rows) = load_tsv("smooth_parity.tsv");
    let x = col(&header, &rows, "x");
    let y_np = col(&header, &rows, "y_numpy");
    let k = 5usize;
    let mine = smooth(&x, k);
    let n = x.len();

    // Interior: identical to numpy's convolve (window fully inside).
    for i in 2..=n - 3 {
        assert!(
            (mine[i] - y_np[i]).abs() < 1e-12,
            "interior[{i}] diverged: {} vs {}",
            mine[i],
            y_np[i]
        );
    }
    // Edges: numpy's zero padding droops; the port must not. The fixture
    // signal has mean ≈ 3, so the drooped numpy edge is visibly smaller.
    assert!(y_np[0] < mine[0], "expected the numpy edge droop the port fixes");
    let clipped_mean = (x[0] + x[1] + x[2]) / 3.0;
    assert!((mine[0] - clipped_mean).abs() < 1e-12, "edge = mean of clipped window");
}
